spring.application.name=courses

spring.datasource.url=jdbc:postgresql://localhost:5432/courses
spring.datasource.username=courses
spring.datasource.password=courses

spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
